"""
Report Generator — Transforms raw AI analysis into structured clinical reports.
Uses an LLM to organize findings into professional radiology report format.
"""

from typing import Optional
from datetime import datetime


REPORT_TEMPLATE = """
RADIOLOGY AI ASSIST REPORT
Generated: {timestamp}
Study Type: {study_type}
Clinical Question: {clinical_question}
AI Provider: {provider} ({model})

{'='*60}
FINDINGS
{'='*60}
{findings}

{'='*60}
INTERPRETATION
{'='*60}
{interpretation}

{'='*60}
DIFFERENTIAL DIAGNOSIS
{'='*60}
{differential}

{'='*60}
AI CONFIDENCE LEVEL: {confidence}
{'='*60}

RECOMMENDATIONS:
{recommendations}

---
DISCLAIMER: This report was generated by an AI assistant and is intended
for educational and research purposes only. It is NOT a certified medical
report and should NOT be used for clinical decision-making without review
by a qualified radiologist.
"""


def format_clinical_report(
    raw_ai_output: str,
    study_type: str,
    clinical_question: str,
    provider: str,
    model: str,
    ai_confidence: Optional[str] = None,
) -> str:
    """
    Parse and format raw AI output into a structured report.
    Uses simple section parsing — assumes AI output has ## sections.
    """
    # Parse sections from AI output
    sections = _parse_ai_sections(raw_ai_output)

    findings = sections.get("findings", raw_ai_output)
    interpretation = sections.get("interpretation", "See findings above.")
    differential = sections.get("differential diagnosis", sections.get("differential", "Not specified."))
    confidence = ai_confidence or sections.get("confidence", sections.get("confidence level", "Not specified."))
    recommendations = sections.get("recommendations", sections.get("recommendation", "None."))

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    return REPORT_TEMPLATE.format(
        timestamp=timestamp,
        study_type=study_type,
        clinical_question=clinical_question,
        provider=provider,
        model=model,
        findings=findings,
        interpretation=interpretation,
        differential=differential,
        confidence=confidence,
        recommendations=recommendations,
    )


def _parse_ai_sections(text: str) -> dict:
    """
    Parse AI output sections from markdown-style headers.
    e.g., "## Findings\nSome text\n## Interpretation\nMore text"
    """
    sections = {}
    current_section = "raw"
    current_content = []

    for line in text.split("\n"):
        line = line.strip()
        if line.startswith("##"):
            # Save previous section
            if current_content:
                sections[current_section.lower()] = "\n".join(current_content).strip()
            # Start new section
            current_section = line.lstrip("#").strip().lower()
            current_content = []
        else:
            current_content.append(line)

    # Save last section
    if current_content:
        sections[current_section.lower()] = "\n".join(current_content).strip()

    return sections


def generate_quick_scan_summary(ai_output: str) -> str:
    """
    Condense AI output into a one-paragraph quick summary.
    Used for the Quick Scan mode (< 10 second response).
    """
    sections = _parse_ai_sections(ai_output)

    finding = sections.get("findings", ai_output[:500])
    confidence = sections.get("confidence", "unknown")

    summary = f"**Quick Scan Result** — Confidence: {confidence}\n\n{finding}"

    if len(summary) > 1000:
        summary = summary[:1000] + "..."

    return summary


def estimate_report_cost(provider: str, num_tokens_approx: int) -> float:
    """
    Estimate cost of a report generation call.
    """
    costs = {
        "ollama": 0.0,
        "kimi": (num_tokens_approx / 1_000_000) * 0.03,      # ~$0.03/1K tokens
        "minimax": (num_tokens_approx / 1_000_000) * 0.29,   # ~$0.29/1M in
        "deepgram": (num_tokens_approx / 60) * 0.0043,       # ~$0.0043/min
    }
    return costs.get(provider, 0.0)
